version: v1.0

plan: standard-2

commands:
  - checkout
  - neetoci-version ruby 3.2.4
  - bundle config path 'vendor/bundle'
  - cache restore
  - bundle install --jobs 1
  - cache store
  - bundle exec rubocop
  - bundle exec rake test
  - bundle exec rspec

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
